### ISSUE TITLE
Add zerolib-flixel dependency requirement to the documentation

### ISSUE THREAD

**Issue by itulau** [01010111/flixel-depth#2]
After some trial and error trying to get the sample to work, I learned that I was missing the [zerolib-flixel](https://github.com/01010111/zerolib-flixel) dependency. I think this could be made clear in the readme that the dependency is necessary in order for Flixel-depth to work, to avoid future misunderstandings like mine :)

**Comment by 01010111** [comment]
Added with bb17097! Sorry for the confusion!
