### ISSUE TITLE
Name collision with HaxeFlixel `container`

### ISSUE THREAD

**Issue by itulau** [01010111/flixel-depth#3]
When trying to build the sample I've noticed an error with the `container` variable from the `DepthCamera` class. It seems because there already is a `container` variable in `FlxBasic` https://github.com/HaxeFlixel/flixel/blob/5ede2bd455af5606115d4b6ffbecb263cf0535f5/flixel/FlxBasic.hx#L78. 

Renaming the variable to something else seems to be making the compiling error to go away.

**Comment by 01010111** [comment]
Fixed with 3cbf04e!
